version: 0.2

run-as: root
env:
#   shell: shell-tag
#   variables:
#     key: "value"
#     key: "value"
    parameter-store:
        AWS_ACCESS_KEY_ID_PARAM: /CodeBuild/AWS_ACCESS_KEY_ID
        AWS_SECRET_ACCESS_KEY_PARAM: /CodeBuild/AWS_SECRET_ACCESS_KEY

phases:
  install:
     run-as: root
#     on-failure: ABORT | CONTINUE
     runtime-versions:
      python: 3.x
#       runtime: version
    
     commands:
      - echo install phase   
      - pip install --upgrade pip
      - pip install awscli
      - aws --version
      - aws configure set aws_access_key_id $AWS_ACCESS_KEY_ID_PARAM
      - aws configure set aws_secret_access_key $AWS_SECRET_ACCESS_KEY_PARAM
      - git --version    
       
     finally:
       - echo install phase completed

  build:
     run-as: root
#     on-failure: ABORT | CONTINUE
     commands:
       - aws ec2 create-key-pair --key-name MyKeyPair --query 'KeyMaterial' --output text > MyKeyPair.pem
       - chmod 400 MyKeyPair.pem
       - git clone https://github.com/haripriya79/simple-website.git
       - cd simple-website
       - sed -i 's/8000/'"$port"'/g' .env
       - INSTANCE_ID=$(aws ec2 run-instances --image-id ami-07eaf2ea4b73a54f6 --count 1 --instance-type t2.micro --key-name MyKeyPair --subnet-id subnet-0ef9c7d5a86c49ffc  --security-group-ids sg-00db824f1b86fcf7f --user-data file://user-data.txt --associate-public-ip-address  --query Instances[*].InstanceId --output text)
       - echo the instance id is $INSTANCE_ID
       - PUBLIC_IP=$(aws ec2 describe-instances --instance-ids $INSTANCE_ID --query Reservations[*].Instances[*].PublicIpAddress --output text)
       - echo public ip address is $PUBLIC_IP
       - cd ..
       - pwd 
       - scp -i MyKeyPair.pem ~/simple-website ec2-user@$PUBLIC_IP:~/var/www/html
artifacts:
  files:
    - '**/*'

   
